<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_participant extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Event_participant_model');
        if (!$this->session->userdata['logged_in']) {
            redirect('/');
        }
    } 

    /*
     * Listing of event_participant
     */
    function index()
    {
        $data['event_participant'] = $this->Event_participant_model->get_all_event_participant();
        
        $data['_view'] = 'event_participant/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new event_participant
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_user' => $this->input->post('id_user'),
				'id_event' => $this->input->post('id_event'),
				'create_at' => $this->input->post('create_at'),
            );
            
            $event_participant_id = $this->Event_participant_model->add_event_participant($params);
            redirect('event_participant/index');
        }
        else
        {            
            $data['_view'] = 'event_participant/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a event_participant
     */
    function edit($)
    {   
        // check if the event_participant exists before trying to edit it
        $data['event_participant'] = $this->Event_participant_model->get_event_participant($);
        
        if(isset($data['event_participant']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_user' => $this->input->post('id_user'),
					'id_event' => $this->input->post('id_event'),
					'create_at' => $this->input->post('create_at'),
                );

                $this->Event_participant_model->update_event_participant($,$params);            
                redirect('event_participant/index');
            }
            else
            {
                $data['_view'] = 'event_participant/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The event_participant you are trying to edit does not exist.');
    } 

    /*
     * Deleting event_participant
     */
    function remove($)
    {
        $event_participant = $this->Event_participant_model->get_event_participant($);

        // check if the event_participant exists before trying to delete it
        if(isset($event_participant['']))
        {
            $this->Event_participant_model->delete_event_participant($);
            redirect('event_participant/index');
        }
        else
            show_error('The event_participant you are trying to delete does not exist.');
    }
    
}
