<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_event extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Event_event_model');
        $this->load->library('session');
        $this->load->library('upload');
        $this->load->helper(array('form', 'url'));
        $this->load->helper('file');
        if (!$this->session->userdata['logged_in']) {
            redirect('/');
        }
    } 

    /*
     * Listing of event_event
     */
    function index()
    {
        if ($this->session->userdata['logged_in']['level'] == 0) {
            $data['event_event'] = $this->Event_event_model->get_all_event_event();
        } else {
            $data['event_event'] = $this->Event_event_model->get_all_event_event_by_creator($this->session->userdata['logged_in']['id_user']);
        } 
        
        $data['_view'] = 'event_event/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new event_event
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name_event','Name Event','required');
		$this->form_validation->set_rules('lokasi','Lokasi','required');
		$this->form_validation->set_rules('pembicara','Pembicara','required');
		$this->form_validation->set_rules('tanggal_mulai','Tanggal Mulai','required');
		$this->form_validation->set_rules('durasi_hari','Durasi Hari','required');
		$this->form_validation->set_rules('jam_mulai','Jam Mulai','required');
		$this->form_validation->set_rules('jam_selesai','Jam Selesai','required');
		$this->form_validation->set_rules('jumlah_tiket','Jumlah Tiket','required');
		$this->form_validation->set_rules('deskripsi_acara','Deskripsi Acara','required');
		
        $config['upload_path']          = './poster/';
        $config['allowed_types']        = 'gif|jpg|png';
        $config['max_size']             = 0;
        $config['max_width']            = 0;
        $config['max_height']           = 0;
        
        $this->load->library('upload', $config);
        $this->upload->initialize($config);
        
        if($this->form_validation->run() && $this->upload->do_upload('poster'))     
        {   
            $namafile = $this->upload->data();
            
            $waktusekarang = date("Y-m-d H:i:s");
            $params = array(
				'id_user' => $this->input->post('id_user'),
				'name_event' => $this->input->post('name_event'),
				'lokasi' => $this->input->post('lokasi'),
				'pembicara' => $this->input->post('pembicara'),
				'tanggal_mulai' => date( "Y-m-d", strtotime($this->input->post('tanggal_mulai'))),
				'durasi_hari' => $this->input->post('durasi_hari'),
				'jam_mulai' => $this->input->post('jam_mulai'),
				'jam_selesai' => $this->input->post('jam_selesai'),
				'jumlah_tiket' => $this->input->post('jumlah_tiket'),
				'poster' => $namafile['file_name'],
				'create_at' => $waktusekarang,
				'deskripsi_acara' => $this->input->post('deskripsi_acara'),
            );
            
            $event_event_id = $this->Event_event_model->add_event_event($params);
            if ($event_event_id) {
                $this->session->set_flashdata('success', 'Berhasil tambah data!');
            } else {
                $this->session->set_flashdata('error', 'Gagal menambahkan data!');
            }
            redirect('event_event/index');
        }
        else
        {            
            $data['_view'] = 'event_event/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a event_event
     */
    public function edit_event_com($id) {
        $data = $this->Event_event_model->get_event_event($id);
        echo json_encode($data);
    }
    /*
     * Editing a event_event
     */
    function edit($id_event)
    {   
        // check if the event_event exists before trying to edit it
        $data['event_event'] = $this->Event_event_model->get_event_event($id_event);
        
        if(isset($data['event_event']['id_event']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name_event','Name Event','required');
			$this->form_validation->set_rules('lokasi','Lokasi','required');
			$this->form_validation->set_rules('pembicara','Pembicara','required');
			$this->form_validation->set_rules('tanggal_mulai','Tanggal Mulai','required');
			$this->form_validation->set_rules('durasi_hari','Durasi Hari','required');
			$this->form_validation->set_rules('jam_mulai','Jam Mulai','required');
			$this->form_validation->set_rules('jam_selesai','Jam Selesai','required');
			$this->form_validation->set_rules('jumlah_tiket','Jumlah Tiket','required');
			$this->form_validation->set_rules('deskripsi_acara','Deskripsi Acara','required');
            
            $config['upload_path']          = './poster/';
            $config['allowed_types']        = 'gif|jpg|png';
            $config['max_size']             = 0;
            $config['max_width']            = 0;
            $config['max_height']           = 0;
            
            $this->load->library('upload', $config);
            $this->upload->initialize($config);
            
			if($this->form_validation->run() && $this->upload->do_upload('poster'))     
            {   
                unlink('./poster/'.$data['event_event']['poster'].'');
                $namafile = $this->upload->data();
                $waktusekarang = date("Y-m-d H:i:s");
                $params = array(
					'id_user' => $this->input->post('id_user'),
					'name_event' => $this->input->post('name_event'),
					'lokasi' => $this->input->post('lokasi'),
					'pembicara' => $this->input->post('pembicara'),
                    //'tanggal_mulai' => $this->input->post('tanggal_mulai'),
                    'tanggal_mulai' => date( "Y-m-d", strtotime($this->input->post('tanggal_mulai'))),
					'durasi_hari' => $this->input->post('durasi_hari'),
					'jam_mulai' => $this->input->post('jam_mulai'),
					'jam_selesai' => $this->input->post('jam_selesai'),
					'jumlah_tiket' => $this->input->post('jumlah_tiket'),
					'poster' => $namafile['file_name'],
					'update_at' => $waktusekarang,
					'deskripsi_acara' => $this->input->post('deskripsi_acara'),
                );

                $this->Event_event_model->update_event_event($id_event,$params);            
                redirect('event_event/index');
            }
            else
            {
                $data['_view'] = 'event_event/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The event_event you are trying to edit does not exist.');
    } 

    /*
     * Deleting event_event
     */
    function remove($id_event)
    {
        $event_event = $this->Event_event_model->get_event_event($id_event);

        // check if the event_event exists before trying to delete it
        if(isset($event_event['id_event']))
        {
            $this->Event_event_model->delete_event_event($id_event);
            $this->session->set_flashdata('success', 'Berhasil tambah data!');
            redirect('event_event/index');
        }
        else
            show_error('The event_event you are trying to delete does not exist.');
            $this->session->set_flashdata('error', 'Gagal menambahkan data!');
    }
    
}
