<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_paper_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_paper by 
     */
    function get_event_paper($)
    {
        return $this->db->get_where('event_paper',array(''=>$))->row_array();
    }
        
    /*
     * Get all event_paper
     */
    function get_all_event_paper()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('event_paper')->result_array();
    }
        
    /*
     * function to add new event_paper
     */
    function add_event_paper($params)
    {
        $this->db->insert('event_paper',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_paper
     */
    function update_event_paper($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('event_paper',$params);
    }
    
    /*
     * function to delete event_paper
     */
    function delete_event_paper($)
    {
        return $this->db->delete('event_paper',array(''=>$));
    }
}
