<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_event by id_event
     */
    function get_event_event($id_event)
    {
        return $this->db->get_where('event_event',array('id_event'=>$id_event))->row();
    }
        
    /*
     * Get all event_event
     */
    function get_all_event_event()
    {
        $this->db->select('id_event, name_event, lokasi, pembicara, tanggal_mulai, jumlah_tiket, deskripsi_acara');
        $this->db->order_by('id_event', 'desc');
        return $this->db->get('event_event')->result_array();
    }
    /*
     * Get all event_event_by_creator
     */
    function get_all_event_event_by_creator($id_user)
    {
        $this->db->select('id_event, name_event, lokasi, pembicara, tanggal_mulai, jumlah_tiket, deskripsi_acara');
        $this->db->where('id_user',$id_user);
        $this->db->order_by('id_event', 'desc');
        return $this->db->get('event_event')->result_array();
    }
        
    /*
     * function to add new event_event
     */
    function add_event_event($params)
    {
        $this->db->insert('event_event',$params);
        return $this->db->insert_id();
    }

    function check_event_event($params)
    {
        $this->db->select('*');
        $this->db->where('id_event',$params);
        return $this->db->get('event_event')->result_array();
    }
    
    /*
     * function to update event_event
     */
    function update_event_event($id_event,$params)
    {
        $this->db->where('id_event',$id_event);
        return $this->db->update('event_event',$params);
    }
    
    /*
     * function to delete event_event
     */
    function delete_event_event($id_event)
    {
        return $this->db->delete('event_event',array('id_event'=>$id_event));
    }

    /*
     * function to tampil peserta
     */
    function tampil_peserta($id)
    {
        $this->db->select('*');
        $this->db->from('event_participant ep');
        $this->db->join('event_event ee','ep.id_event = ee.id_event');
        $this->db->join('event_users eu','ep.id_user = eu.id_user');
        $this->db->where('ee.id_event='.$id.'');
        $this->db->order_by('ep.create_at', 'desc');
        $data = $this->db->get()->result_array();
        return $data;
    }
}
