<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_paper_riview_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_paper_riview by id_paper
     */
    function get_event_paper_riview($id_paper)
    {
        return $this->db->get_where('event_paper_riview',array('id_paper'=>$id_paper))->row_array();
    }
        
    /*
     * Get all event_paper_riview
     */
    function get_all_event_paper_riview()
    {
        $this->db->order_by('id_paper', 'desc');
        return $this->db->get('event_paper_riview')->result_array();
    }
        
    /*
     * function to add new event_paper_riview
     */
    function add_event_paper_riview($params)
    {
        $this->db->insert('event_paper_riview',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_paper_riview
     */
    function update_event_paper_riview($id_paper,$params)
    {
        $this->db->where('id_paper',$id_paper);
        return $this->db->update('event_paper_riview',$params);
    }
    
    /*
     * function to delete event_paper_riview
     */
    function delete_event_paper_riview($id_paper)
    {
        return $this->db->delete('event_paper_riview',array('id_paper'=>$id_paper));
    }
}
