<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_participant_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_participant by 
     */
    function get_event_participant($)
    {
        return $this->db->get_where('event_participant',array(''=>$))->row_array();
    }
        
    /*
     * Get all event_participant
     */
    function get_all_event_participant()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('event_participant')->result_array();
    }
        
    /*
     * function to add new event_participant
     */
    function add_event_participant($params)
    {
        $this->db->insert('event_participant',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_participant
     */
    function update_event_participant($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('event_participant',$params);
    }
    
    /*
     * function to delete event_participant
     */
    function delete_event_participant($)
    {
        return $this->db->delete('event_participant',array(''=>$));
    }
}
